version: '3'
services:
  web:
      restart: always
      build: 
        context: .
        dockerfile: Dockerfile
      image: "k8s.net.demo"
      container_name: "k8s.net.demo"
      # image: k8s.net.demo
      ports:
       - "8200:80"
  # mysql:
  #     container_name: mysql_dc
  #     restart: always
  #     environment:
  #       MYSQL_DATABASE: blogdb
  #       MYSQL_ROOT_PASSWORD : qwer1234!
  #     image: mysql:5.6
  #     ports:
  #       - "3306:3306"
  #     command: [
  #        '--character-set-server=utf8',
  #        '--collation-server=utf8_unicode_ci'
  #     ]